//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpTables.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mpTables.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MpTables_16x16 {
            get {
                object obj = ResourceManager.GetObject("MpTables_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MpTables_32x32 {
            get {
                object obj = ResourceManager.GetObject("MpTables_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Tables {
            get {
                object obj = ResourceManager.GetObject("Tables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Tables&gt;
        ///	&lt;Documents&gt;
        ///		&lt;Document document=&quot;СТБ 2255-2012&quot; name=&quot;СПДС. Основные требования к документации строительного проекта&quot;&gt;&lt;/Document&gt;
        ///	&lt;/Documents&gt;
        ///	&lt;Table
        ///	name=&quot;Ведомость чертежей основного комплекта&quot;
        ///	tablestylename=&quot;Mp_STB_2255_B1&quot;
        ///	document=&quot;СТБ 2255-2012&quot;
        ///	description=&quot;Приложение Б. Рисунок Б.1&quot;
        ///	img=&quot;img_0&quot;
        ///	DataRow=&quot;2&quot;
        ///    DynRow=&quot;True&quot;
        ///    NameToHeader=&quot;True&quot;
        ///	&gt;&lt;/Table&gt;
        ///	&lt;Table
        ///	name=&quot;Ведомость спецификаций&quot;
        ///	tablestylename=&quot;Mp_S [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TablesBase_BY {
            get {
                return ResourceManager.GetString("TablesBase_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Tables&gt;
        ///	&lt;Documents&gt;
        ///		&lt;Document document=&quot;ГОСТ Р 21.1101-2013&quot; name=&quot;СПДС. Основные требования к проектной и рабочей документации&quot;&gt;&lt;/Document&gt;
        ///		&lt;Document document=&quot;ГОСТ 21.508-93&quot; name=&quot;СПДС. Правила выполнения рабочей документации генеральных планов предприятий, сооружений и жилищно-гражданских объектов&quot;&gt;&lt;/Document&gt;
        ///		&lt;Document document=&quot;ГОСТ 21.501-2011&quot; name=&quot;СПДС. Правила выполнения архитектурно-строительных рабочих чертежей&quot;&gt;&lt;/Document&gt;
        ///		&lt;Document [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TablesBase_RU {
            get {
                return ResourceManager.GetString("TablesBase_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;Tables&gt;
        ///	&lt;Documents&gt;
        ///		&lt;Document document=&quot;ДСТУ Б А.2.4-4:2009&quot; name=&quot;СПДС. Основні вимоги до проектної та робочої документації&quot;&gt;&lt;/Document&gt;
        ///	&lt;/Documents&gt;
        ///	&lt;Table
        ///	name=&quot;Відомість робочих креслень основного комплекту&quot;
        ///	tablestylename=&quot;Mp_DSTU_B_A.2.4-4_F1&quot;
        ///	document=&quot;ДСТУ Б А.2.4-4:2009&quot;
        ///	description=&quot;Додаток Б. Форма 1&quot;
        ///	img=&quot;img_0&quot;
        ///	DataRow=&quot;2&quot;
        ///    DynRow=&quot;True&quot;
        ///    NameToHeader=&quot;True&quot;
        ///	&gt;&lt;/Table&gt;
        ///	&lt;Table
        ///	name=&quot;Відомості специфікацій&quot;
        ///	tables [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TablesBase_UA {
            get {
                return ResourceManager.GetString("TablesBase_UA", resourceCulture);
            }
        }
    }
}
